name: Build and Push

permissions:
  contents: read
  actions: read
  checks: write

on:
  push:


jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build and Run Tests
        run: mvn clean test

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name:  report unittests
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

  docker-build-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build the application JAR
        run: mvn clean package -DskipTests  # This builds the JAR file

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t wafik97/reading-sync-service:${{ github.run_number }} .

      - name: Push Docker image to DockerHub
        run: |
          docker push wafik97/reading-sync-service:${{ github.run_number }}